### ISSUE TITLE
没有安装包吗

### ISSUE THREAD

**Issue by kelvinchanjl** [eli-jordan/alfred-jenkins#46]
安装包找不到

**Comment by eli-jordan** [comment]
Sorry I don’t know Chinese.

**Comment by kelvinchanjl** [comment]
How to install?Do you have the installation package?

**Comment by eli-jordan** [comment]
You can download from the actions tab. I haven’t released an official version yet https://github.com/eli-jordan/alfred-jenkins/actions/runs/655183463

**Comment by kelvinchanjl** [comment]
think you very much
